In [36]:
import pandas as pd
import numpy as np

In [37]:
dataset = pd.read_csv('Student_data.csv')
print(dataset)

         Name  CAT1  CAT2  CAT3  Attendence  Semester Marks
0   sathyadev    43    45    47           5              91
1        anbu    23    26    21           2              46
2    hemanika    48    49    50           5              98
3      pandya    32    40    35           4              72
4        rani    45    50    42           5              92
5       raghu    43    41    42           5              85
6       lekha    34    37    41           4              75
7      victor    12    23    24           2              39
8      mathew    23    24    28           3              51
9     amudhan    43    46    47           4              90
10   raghavan    50    49    49           5              99
11   aaratana    49    48    47           5              96
12  venkatesh    26    29    31           4              58
13    kalyani    34    47    31           5              76
14  ilamaaran    34    48    46           5              86
15      thiru    41    42    42         

In [44]:
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values
print(y)
print(X)

[91 46 98 72 92 85 75 39 51 90 99 96 58 76 86 84 94 66 92 96]
[[43 45 47  5]
 [23 26 21  2]
 [48 49 50  5]
 [32 40 35  4]
 [45 50 42  5]
 [43 41 42  5]
 [34 37 41  4]
 [12 23 24  2]
 [23 24 28  3]
 [43 46 47  4]
 [50 49 49  5]
 [49 48 47  5]
 [26 29 31  4]
 [34 47 31  5]
 [34 48 46  5]
 [41 42 42  5]
 [47 45 48  5]
 [32 34 33  3]
 [45 44 48  5]
 [48 49 46  5]]


In [72]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [73]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [74]:
y_pred = regressor.predict(X_test)
print(y_pred)

[91.79 46.07 95.71 50.18 98.86 65.54 74.8  76.14]


In [75]:
print(y_test)

[92 46 96 51 99 66 75 76]


In [76]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[91.79 92.  ]
 [46.07 46.  ]
 [95.71 96.  ]
 [50.18 51.  ]
 [98.86 99.  ]
 [65.54 66.  ]
 [74.8  75.  ]
 [76.14 76.  ]]
